CREATE DATABASE SENAI_ROMAN

---------------SQL---------------
---------------DDL---------------

USE SENAI_ROMAN;

CREATE TABLE TIPO_USUARIO (
	ID INT IDENTITY  PRIMARY KEY NOT NULL,
	TIPO VARCHAR(255) NOT NULL UNIQUE
);
GO

CREATE TABLE TEMAS (
	ID INT IDENTITY  PRIMARY KEY NOT NULL,
	TEMAS VARCHAR(255) NOT NULL UNIQUE
);
GO

CREATE TABLE USUARIOS (
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	ID_TIPOUSUARIO INT FOREIGN KEY REFERENCES TIPO_USUARIO(ID) NOT NULL,
	NOME_USU VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	SENHA VARCHAR(255) NOT NULL
);
GO

CREATE TABLE PROJETOS (
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	ID_TEMA INT FOREIGN KEY REFERENCES TEMAS(ID) NOT NULL,
	ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID) NOT NULL,
	NOME_PRO VARCHAR(255) NOT NULL,
	DESCRICAO_PRO VARCHAR(255) NOT NULL,
);
GO